name = "MyTest"
author = "okou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d516b4659e09633873faf904afaf4981d7e1286318bb590bccd3568de7d5c2a7"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
